In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
import datetime as dt

In [2]:
#List of datasets
data1 = "olist_customers_dataset.csv"
data2 = "olist_order_items_dataset.csv"
data3 = "olist_order_payments_dataset.csv"
data4 = "olist_order_reviews_dataset.csv"
data5 = "olist_orders_dataset.csv"
data6 = "olist_products_dataset.csv"
data7 = "olist_sellers_dataset.csv"

In [3]:
#customer dataset
customer = pd.read_csv(data1)

customer

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [4]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [5]:
order_items = pd.read_csv(data2)

order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,19/09/2017 09:45,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,03/05/2017 11:05,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,18/01/2018 14:48,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,15/08/2018 10:10,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13/02/2017 13:57,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,02/05/2018 04:11,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,20/07/2018 04:31,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,30/10/2017 17:14,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,21/08/2017 00:04,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,12/06/2018 17:10,43.00,12.79

In [6]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [7]:
order_payments = pd.read_csv(data3)

order_payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [8]:
order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [9]:
order_reviews = pd.read_csv(data4)

order_reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,18/01/2018 00:00,18/01/2018 21:46
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,10/03/2018 00:00,11/03/2018 03:05
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,17/02/2018 00:00,18/02/2018 14:36
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,21/04/2017 00:00,21/04/2017 22:02
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,01/03/2018 00:00,02/03/2018 10:26
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,07/07/2018 00:00,14/07/2018 17:18
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,09/12/2017 00:00,11/12/2017 20:06
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",22/03/2018 00:00,23/03/2018 09:10
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,01/07/2018 00:00,02/07/2018 12:59
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",03/07/2017 00:00,03/07/2017 21:01

In [10]:
order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [11]:
orders = pd.read_csv(data5)

orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02/10/2017 10:56,02/10/2017 11:07,04/10/2017 19:55,10/10/2017 21:25,18/10/2017 00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,24/07/2018 20:41,26/07/2018 03:24,26/07/2018 14:31,07/08/2018 15:27,13/08/2018 00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,08/08/2018 08:38,08/08/2018 08:55,08/08/2018 13:50,17/08/2018 18:06,04/09/2018 00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,18/11/2017 19:28,18/11/2017 19:45,22/11/2017 13:39,02/12/2017 00:28,15/12/2017 00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,13/02/2018 21:18,13/02/2018 22:20,14/02/2018 19:46,16/02/2018 18:17,26/02/2018 00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,09/03/2017 09:54,09/03/2017 09:54,10/03/2017 11:18,17/03/2017 15:08,28/03/2017 00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,06/02/2018 12:58,06/02/2018 13:10,07/02/2018 23:22,28/02/2018 17:37,02/03/2018 00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,27/08/2017 14:46,27/08/2017 15:04,28/08/2017 20:52,21/09/2017 11:24,27/09/2017 00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,08/01/2018 21:28,08/01/2018 21:36,12/01/2018 15:35,25/01/2018 23:32,15/02/2018 00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,08/03/2018 20:57,09/03/2018 11:20,09/03/2018 22:11,16/03/2018 13:08,03/04/2018 00:00

In [12]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [13]:
products = pd.read_csv(data6)

products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [14]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [15]:
sellers = pd.read_csv(data7)

sellers

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [16]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

**Dropping the duplicates from the rows**

In [17]:

customer.drop_duplicates()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [18]:

order_items.drop_duplicates()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,19/09/2017 09:45,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,03/05/2017 11:05,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,18/01/2018 14:48,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,15/08/2018 10:10,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13/02/2017 13:57,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,02/05/2018 04:11,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,20/07/2018 04:31,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,30/10/2017 17:14,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,21/08/2017 00:04,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,12/06/2018 17:10,43.00,12.79

In [19]:

order_payments.drop_duplicates()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [20]:

order_reviews.drop_duplicates()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,18/01/2018 00:00,18/01/2018 21:46
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,10/03/2018 00:00,11/03/2018 03:05
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,17/02/2018 00:00,18/02/2018 14:36
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,21/04/2017 00:00,21/04/2017 22:02
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,01/03/2018 00:00,02/03/2018 10:26
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,07/07/2018 00:00,14/07/2018 17:18
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,09/12/2017 00:00,11/12/2017 20:06
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",22/03/2018 00:00,23/03/2018 09:10
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,01/07/2018 00:00,02/07/2018 12:59
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",03/07/2017 00:00,03/07/2017 21:01

In [21]:

orders.drop_duplicates()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02/10/2017 10:56,02/10/2017 11:07,04/10/2017 19:55,10/10/2017 21:25,18/10/2017 00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,24/07/2018 20:41,26/07/2018 03:24,26/07/2018 14:31,07/08/2018 15:27,13/08/2018 00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,08/08/2018 08:38,08/08/2018 08:55,08/08/2018 13:50,17/08/2018 18:06,04/09/2018 00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,18/11/2017 19:28,18/11/2017 19:45,22/11/2017 13:39,02/12/2017 00:28,15/12/2017 00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,13/02/2018 21:18,13/02/2018 22:20,14/02/2018 19:46,16/02/2018 18:17,26/02/2018 00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,09/03/2017 09:54,09/03/2017 09:54,10/03/2017 11:18,17/03/2017 15:08,28/03/2017 00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,06/02/2018 12:58,06/02/2018 13:10,07/02/2018 23:22,28/02/2018 17:37,02/03/2018 00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,27/08/2017 14:46,27/08/2017 15:04,28/08/2017 20:52,21/09/2017 11:24,27/09/2017 00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,08/01/2018 21:28,08/01/2018 21:36,12/01/2018 15:35,25/01/2018 23:32,15/02/2018 00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,08/03/2018 20:57,09/03/2018 11:20,09/03/2018 22:11,16/03/2018 13:08,03/04/2018 00:00

In [22]:

products.drop_duplicates()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [23]:

sellers.drop_duplicates()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

**Checking for Null Values and fixing it**

In [24]:
customer.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [25]:
order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [26]:
order_payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [27]:
order_reviews.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

There are multiple null values in review_comment_title and review_comment_message, so I am going to drop the rows, plus it isn't need for the analysis.

In [28]:
order_reviews = order_reviews.drop(columns=['review_comment_title', 'review_comment_message'])

order_reviews.isna().sum()

review_id                  0
order_id                   0
review_score               0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [29]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [30]:
orders = orders.dropna(subset=['order_approved_at', 'order_delivered_carrier_date', 
                              'order_delivered_customer_date'])
orders.isna().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

In [31]:
products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [32]:
products = products.dropna(subset=['product_category_name', 'product_name_lenght', 
                              'product_description_lenght', 'product_photos_qty','product_weight_g','product_length_cm','product_height_cm','product_width_cm'])

products.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [33]:
sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [34]:
#converting date columns
#ORDERITEMS TABLE


order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])
order_items['shipping_limit_date'] = order_items['shipping_limit_date'].dt.date
print(order_items.info())


#Order review table
data_col1 = ['review_creation_date', 'review_answer_timestamp']

for i in data_col1:
    order_reviews[i] = pd.to_datetime(order_reviews[i]).dt.date

print(order_reviews.info())
#ORDERS TABLE

data_col2 = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

for i in data_col2:
    orders[i] = pd.to_datetime(orders[i], format='mixed')
    
print(orders.info())

C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1838738487.py:5: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None

C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1838738487.py:14: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  order_reviews[i] = pd.to_datetime(order_reviews[i]).dt.date
C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1838738487.py:14: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  order_reviews[i] = pd.to_datetime(order_reviews[i]).dt.date

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_creation_date     99224 non-null  object
 4   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1838738487.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[i] = pd.to_datetime(orders[i], format='mixed')
C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1838738487.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[i] = pd.to_datetime(orders[i], format='mixed')
C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1838738487.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[i] = pd.to_datetime(orders[i], format='mixed')
C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1838738487.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[i] = pd.to_datetime(orders[i], format='mixed')
C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1838738487.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[i] = pd.to_datetime(orders[i], format='mixed')

<class 'pandas.core.frame.DataFrame'>
Index: 96461 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96461 non-null  object
 1   customer_id                    96461 non-null  object
 2   order_status                   96461 non-null  object
 3   order_purchase_timestamp       96461 non-null  datetime64[ns]
 4   order_approved_at              96461 non-null  datetime64[ns]
 5   order_delivered_carrier_date   96461 non-null  datetime64[ns]
 6   order_delivered_customer_date  96461 non-null  datetime64[ns]
 7   order_estimated_delivery_date  96461 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.6+ MB
None

In [35]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-02-10 10:56:00,2017-02-10 11:07:00,2017-04-10 19:55:00,2017-10-10 21:25:00,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-07-08 15:27:00,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-04-09
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-02-12 00:28:00,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-09-03 09:54:00,2017-09-03 09:54:00,2017-10-03 11:18:00,2017-03-17 15:08:00,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-06-02 12:58:00,2018-06-02 13:10:00,2018-07-02 23:22:00,2018-02-28 17:37:00,2018-02-03
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-08-28 20:52:00,2017-09-21 11:24:00,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-08-01 21:28:00,2018-08-01 21:36:00,2018-12-01 15:35:00,2018-01-25 23:32:00,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-08-03 20:57:00,2018-09-03 11:20:00,2018-09-03 22:11:00,2018-03-16 13:08:00,2018-03-04

**FEATURE ENGINEERING**

In [36]:
#DELIVERY TIME

orders['delivery_time'] = orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']

orders['delivery_time'] = orders['delivery_time'].dt.days
orders.head(5)

C:\Users\bless\AppData\Local\Temp\ipykernel_17492\3575737259.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['delivery_time'] = orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']
C:\Users\bless\AppData\Local\Temp\ipykernel_17492\3575737259.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['delivery_time'] = orders['delivery_time'].dt.days

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-02-10 10:56:00,2017-02-10 11:07:00,2017-04-10 19:55:00,2017-10-10 21:25:00,2017-10-18,242
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-07-08 15:27:00,2018-08-13,-17
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-04-09,9
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-02-12 00:28:00,2017-12-15,-280
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,2

In [37]:
#Estimated delivery day

orders['estimated_delivery_day'] = orders['order_estimated_delivery_date'] - orders['order_purchase_timestamp']

orders['estimated_delivery_day'] = orders['estimated_delivery_day'].dt.days

C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1402790167.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['estimated_delivery_day'] = orders['order_estimated_delivery_date'] - orders['order_purchase_timestamp']
C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1402790167.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['estimated_delivery_day'] = orders['estimated_delivery_day'].dt.days

In [38]:
#Convert both to datetime

orders['delivery_time'] = pd.to_datetime(orders['delivery_time'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

C:\Users\bless\AppData\Local\Temp\ipykernel_17492\2850867519.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['delivery_time'] = pd.to_datetime(orders['delivery_time'])
C:\Users\bless\AppData\Local\Temp\ipykernel_17492\2850867519.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

In [39]:
#late delivery 
# we will assume late delivery is any oder that arrived more than 7 days later

orders['late_delivery'] = orders['delivery_time'] > orders['order_estimated_delivery_date']


orders.head(5)

C:\Users\bless\AppData\Local\Temp\ipykernel_17492\1619517721.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['late_delivery'] = orders['delivery_time'] > orders['order_estimated_delivery_date']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time,estimated_delivery_day,late_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-02-10 10:56:00,2017-02-10 11:07:00,2017-04-10 19:55:00,2017-10-10 21:25:00,2017-10-18,1970-01-01 00:00:00.000000242,249,False
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-07-08 15:27:00,2018-08-13,1969-12-31 23:59:59.999999983,19,False
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-04-09,1970-01-01 00:00:00.000000009,-122,False
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-02-12 00:28:00,2017-12-15,1969-12-31 23:59:59.999999720,26,False
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,1970-01-01 00:00:00.000000002,12,False

In [40]:
orders['delivery_time'] = (
    orders['order_delivered_customer_date'] 
    - orders['order_purchase_timestamp']
).dt.days

C:\Users\bless\AppData\Local\Temp\ipykernel_17492\2658437537.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders['delivery_time'] = (

In [41]:
order_items["profit"] = order_items["price"] - order_items["freight_value"]

In [42]:
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,profit
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19,58.90,13.29,45.61
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03,239.90,19.93,219.97
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18,199.00,17.87,181.13
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15,12.99,12.79,0.20
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13,199.90,18.14,181.76
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02,299.99,43.41,256.58
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20,350.00,36.53,313.47
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30,99.90,16.95,82.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21,55.99,8.72,47.27
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12,43.00,12.79,30.21

In [43]:
customer

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [44]:
#because snowflake automaticall uppercases everything
customer.columns = customer.columns.str.upper()
orders.columns = orders.columns.str.upper()
order_items.columns = order_items.columns.str.upper()
order_payments.columns = order_payments.columns.str.upper()
order_reviews.columns = order_reviews.columns.str.upper()
products.columns = products.columns.str.upper()
sellers.columns = sellers.columns.str.upper()

In [45]:
type(order_payments)

pandas.core.frame.DataFrame

In [47]:
!pip install snowflake

Collecting snowflake
  Downloading snowflake-1.12.0-py3-none-any.whl.metadata (2.0 kB)
Collecting snowflake-core==1.12.0 (from snowflake)
  Downloading snowflake_core-1.12.0-py3-none-any.whl.metadata (2.2 kB)
Collecting snowflake-legacy (from snowflake)
  Downloading snowflake_legacy-1.0.2-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: certifi in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-core==1.12.0->snowflake) (2025.11.12)
Requirement already satisfied: pydantic>=2 in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-core==1.12.0->snowflake) (2.12.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-core==1.12.0->snowflake) (2.9.0.post0)
Requirement already satisfied: pyyaml in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-core==1.12.0->snowflake) (6.0.3)
Requirement already satisfied: requests in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-core==1.12.0->snowflake) (2.32.5)
Collecting snowflake-connector-python (from snowflake-core==1.12.0->snowflake)
  Downloading snowflake_connector_python-4.4.0-cp313-cp313-win_amd64.whl.metadata (83 kB)
Requirement already satisfied: urllib3 in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-core==1.12.0->snowflake) (2.5.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\bless\downloads\anaconda\lib\site-packages (from pydantic>=2->snowflake-core==1.12.0->snowflake) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\bless\downloads\anaconda\lib\site-packages (from pydantic>=2->snowflake-core==1.12.0->snowflake) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\bless\downloads\anaconda\lib\site-packages (from pydantic>=2->snowflake-core==1.12.0->snowflake) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\bless\downloads\anaconda\lib\site-packages (from pydantic>=2->snowflake-core==1.12.0->snowflake) (0.4.2)
Requirement already satisfied: six>=1.5 in c:\users\bless\downloads\anaconda\lib\site-packages (from python-dateutil>=2.8.2->snowflake-core==1.12.0->snowflake) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\bless\downloads\anaconda\lib\site-packages (from requests->snowflake-core==1.12.0->snowflake) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bless\downloads\anaconda\lib\site-packages (from requests->snowflake-core==1.12.0->snowflake) (3.11)
Collecting asn1crypto<2.0.0,>0.24.0 (from snowflake-connector-python->snowflake-core==1.12.0->snowflake)
  Using cached asn1crypto-1.5.1-py2.py3-none-any.whl.metadata (13 kB)
Collecting cryptography>=46.0.5 (from snowflake-connector-python->snowflake-core==1.12.0->snowflake)
  Downloading cryptography-46.0.7-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Requirement already satisfied: pyOpenSSL>=24.0.0 in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-connector-python->snowflake-core==1.12.0->snowflake) (25.3.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-connector-python->snowflake-core==1.12.0->snowflake) (2.10.1)
Requirement already satisfied: pytz in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-connector-python->snowflake-core==1.12.0->snowflake) (2025.2)
Requirement already satisfied: packaging in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-connector-python->snowflake-core==1.12.0->snowflake) (25.0)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-connector-python->snowflake-core==1.12.0->snowflake) (3.20.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-connector-python->snowflake-core==1.12.0->snowflake) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-connector-python->snowflake-core==1.12.0->snowflake) (4.5.0)
Requirement already satisfied: tomlkit in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-connector-python->snowflake-core==1.12.0->snowflake) (0.13.3)
Collecting boto3>=1.24 (from snowflake-connector-python->snowflake-core==1.12.0->snowflake)
  Downloading boto3-1.42.94-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: botocore>=1.24 in c:\users\bless\downloads\anaconda\lib\site-packages (from snowflake-connector-python->snowflake-core==1.12.0->snowflake) (1.40.46)
Collecting botocore>=1.24 (from snowflake-connector-python->snowflake-core==1.12.0->snowflake)
  Downloading botocore-1.42.94-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\bless\downloads\anaconda\lib\site-packages (from boto3>=1.24->snowflake-connector-python->snowflake-core==1.12.0->snowflake) (1.0.1)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3>=1.24->snowflake-connector-python->snowflake-core==1.12.0->snowflake)
  Downloading s3transfer-0.16.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: cffi>=2.0.0 in c:\users\bless\downloads\anaconda\lib\site-packages (from cryptography>=46.0.5->snowflake-connector-python->snowflake-core==1.12.0->snowflake) (2.0.0)
Requirement already satisfied: pycparser in c:\users\bless\downloads\anaconda\lib\site-packages (from cffi>=2.0.0->cryptography>=46.0.5->snowflake-connector-python->snowflake-core==1.12.0->snowflake) (2.23)
Downloading snowflake-1.12.0-py3-none-any.whl (5.6 kB)
Downloading snowflake_core-1.12.0-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 9.7 MB/s  0:00:00
Downloading snowflake_connector_python-4.4.0-cp313-cp313-win_amd64.whl (12.1 MB)
   ---------------------------------------- 0.0/12.1 MB ? eta -:--:--
   ------------------------- -------------- 7.6/12.1 MB 37.0 MB/s eta 0:00:01
   ---------------------------------------- 12.1/12.1 MB 33.7 MB/s  0:00:00
Using cached asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
Downloading boto3-1.42.94-py3-none-any.whl (140 kB)
Downloading botocore-1.42.94-py3-none-any.whl (14.9 MB)
   ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
   ------------------------- -------------- 9.4/14.9 MB 53.7 MB/s eta 0:00:01
   ---------------------------------------- 14.9/14.9 MB 45.6 MB/s  0:00:00
Downloading s3transfer-0.16.1-py3-none-any.whl (86 kB)
Downloading cryptography-46.0.7-cp311-abi3-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 3.5/3.5 MB 35.5 MB/s  0:00:00
Downloading snowflake_legacy-1.0.2-py3-none-any.whl (3.1 kB)
Installing collected packages: asn1crypto, snowflake-legacy, cryptography, botocore, s3transfer, boto3, snowflake-connector-python, snowflake-core, snowflake

   ---------------------------------------- 0/9 [asn1crypto]
  Attempting uninstall: cryptography
   ---------------------------------------- 0/9 [asn1crypto]
    Found existing installation: cryptography 46.0.3
   ---------------------------------------- 0/9 [asn1crypto]
   -------- ------------------------------- 2/9 [cryptography]
    Uninstalling cryptography-46.0.3:
   -------- ------------------------------- 2/9 [cryptography]
      Successfully uninstalled cryptography-46.0.3
   -------- ------------------------------- 2/9 [cryptography]
   -------- ------------------------------- 2/9 [cryptography]
   -------- ------------------------------- 2/9 [cryptography]
   -------- ------------------------------- 2/9 [cryptography]
   -------- ------------------------------- 2/9 [cryptography]
  Attempting uninstall: botocore
   -------- ------------------------------- 2/9 [cryptography]
    Found existing installation: botocore 1.40.46
   -------- ------------------------------- 2/9 [cryptography]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
    Uninstalling botocore-1.40.46:
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
      Successfully uninstalled botocore-1.40.46
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ------------- -------------------------- 3/9 [botocore]
   ----------------- ---------------------- 4/9 [s3transfer]
   ---------------------- ----------------- 5/9 [boto3]
   ---------------------- ----------------- 5/9 [boto3]
   ---------------------- ----------------- 5/9 [boto3]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   -------------------------- ------------- 6/9 [snowflake-connector-python]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ------------------------------- -------- 7/9 [snowflake-core]
   ---------------------------------------- 9/9 [snowflake]

Successfully installed asn1crypto-1.5.1 boto3-1.42.94 botocore-1.42.94 cryptography-46.0.7 s3transfer-0.16.1 snowflake-1.12.0 snowflake-connector-python-4.4.0 snowflake-core-1.12.0 snowflake-legacy-1.0.2

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.25.0 requires botocore<1.40.50,>=1.40.46, but you have botocore 1.42.94 which is incompatible.

In [48]:
import snowflake.connector

ctx = snowflake.connector.connect(
    user='BLESSING',
    password="Chichi7muanya*",
    account='LGVNQED-JM24686', # e.g., xy12345.us-east-2
    warehouse='COMPUTE_WH',
    database='ECOMMERCE_DB',
    schema='RAW'
) 

conn = ctx

from snowflake.connector.pandas_tools import write_pandas

write_pandas(conn, customer, "CUSTOMER_RAW", schema="RAW")
write_pandas(conn, orders, "ORDERS_RAW", schema="RAW")
write_pandas(conn, order_items, "ORDER_ITEMS_RAW", schema="RAW")
write_pandas(conn, order_payments, "ORDER_PAYMENTS_RAW", schema="RAW")
write_pandas(conn, order_reviews, "ORDER_REVIEWS_RAW", schema="RAW")
write_pandas(conn, products, "PRODUCT_RAW", schema="RAW")
write_pandas(conn, sellers, "SELLERS_RAW", schema="RAW")

C:\Users\bless\AppData\Local\Temp\ipykernel_17492\46636593.py:17: UserWarning: Pandas Dataframe has non-standard index of type <class 'pandas.core.indexes.base.Index'> which will not be written. Consider changing the index to pd.RangeIndex(start=0,...,step=1) or call reset_index() to keep index as column(s)
  write_pandas(conn, orders, "ORDERS_RAW", schema="RAW")
C:\Users\bless\AppData\Local\Temp\ipykernel_17492\46636593.py:21: UserWarning: Pandas Dataframe has non-standard index of type <class 'pandas.core.indexes.base.Index'> which will not be written. Consider changing the index to pd.RangeIndex(start=0,...,step=1) or call reset_index() to keep index as column(s)
  write_pandas(conn, products, "PRODUCT_RAW", schema="RAW")

(True,
 1,
 3095,
 [('snowpark_temp_stage_8yxrql0p8t/file0.txt',
   'LOADED',
   3095,
   3095,
   1,
   0,
   None,
   None,
   None,
   None)])